[plugins]
kotlin = { id = "me.mh.apps.settings.plugins.spring.kotlin" }
spring-boot = { id = "me.mh.apps.settings.plugins.spring.boot" }
spring-web = { id = "me.mh.apps.settings.plugins.spring.web" }
spring-batch = { id = "me.mh.apps.settings.plugins.spring.batch" }
spring-jpa = { id = "me.mh.apps.settings.plugins.spring.jpa" }
querydsl = { id = "me.mh.apps.settings.plugins.querydsl" }
jooq = { id = "me.mh.apps.settings.plugins.spring.jooq" }
