[versions]
app = "1.0.0"
java = "21"
kotlin = "1.9.25"
springBoot = "3.5.6"
springDependencyManagement = "1.1.7"
jooq = "3.19.26"
google-devTools-ksp = "1.9.25-1.0.20"
openfeign-querydsl = "7.1"

[plugins]
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependencyManagement = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }

me-kotlin = { id = "me.mh.apps.settings.plugins.spring.kotlin" }
me-spring-boot = { id = "me.mh.apps.settings.plugins.spring.boot" }
me-spring-web = { id = "me.mh.apps.settings.plugins.spring.web" }
me-spring-batch = { id = "me.mh.apps.settings.plugins.spring.batch" }
me-spring-jpa = { id = "me.mh.apps.settings.plugins.spring.jpa" }
me-querydsl = { id = "me.mh.apps.settings.plugins.spring.querydsl" }
me-jooq = { id = "me.mh.apps.settings.plugins.spring.jooq" }