[versions]
app = "1.0.0"
java = "21"
kotlin = "1.9.25"
springBoot = "3.5.6"
springDependencyManagement = "1.1.7"
jooq = "3.19.26"
junit5 = "5.12.2"

[plugins]
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependencyManagement = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }